### PR TITLE
Release v2.3.3

### PR DESCRIPTION
**Pull request by lushkant**
* Fixes Twitter widget not rendering tweets
* Deprecate Instagram widget

### CODE REVIEW

**Comment by mauryaratan** [comment]
@lushkant Did you test with WordPress 5.5?

**Comment by lushkant** [comment]
@mauryaratan yes this was with 5.5 beta 1

**Comment by mauryaratan** [comment]
@lushkant In that case, lets bump the "Tested up to" header in readme

**Comment by lushkant** [comment]
done!

**Pull request merged**
